Server/Server/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('funk.urls'))
]

Server/funk/urls.py
from django.contrib.auth.views import login as login_view
from django.contrib.auth.views import logout as logout_view
from django.conf.urls import url
from django.views.generic.base import TemplateView

from funk.views import CreateBranch, ShowDash, SearchBranch, RemoveBranch, EditBranch, CreateBranchHead, \
    SearchBranchHead, EditBranchHead, RemoveBranchHead, CreateEmployee, SearchEmployee, EditEmployee, RemoveEmployee, \
    CreateCustomer, SearchCustomer, ActivateCustomer, CreateAccount, SearchCustomerAjax, BanSearchAccount, BanAccount

app_name = 'funk'
urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='funk/Welcome.html'), name='home'),

    url(r'^ajax/usersearch/$', SearchCustomerAjax.as_view(), name='search_user_ajax'),

    url(r'^login/$', login_view, {'template_name': 'funk/login.html'},  name='login'),
    url(r'^logout/$', logout_view,{'next_page': '/'}, name='logout'),
    url(r'^dash/$', ShowDash.as_view(), name='dash'),

    url(r'^dash/branch/creation/$', CreateBranch.as_view(), name='branch_creation'),
    url(r'^dash/branch/search/$', SearchBranch.as_view(), name='branch_search'),
    url(r'^dash/branch/delete/(?P<branch_id>[0-9]+)/$', RemoveBranch.as_view(), name='branch_delete'),
    url(r'^dash/branch/edit/(?P<branch_id>[0-9]+)/$', EditBranch.as_view(), name='branch_edit'),


    url(r'^dash/employee/head/creation/$', CreateBranchHead.as_view(), name='branch_head_creation'),
    url(r'^dash/employee/head/search/$', SearchBranchHead.as_view(), name='branch_head_search'),
    url(r'^dash/employee/head/edit/(?P<head_id>[0-9]+)/$', EditBranchHead.as_view(), name='branch_head_edit'),
    url(r'^dash/employee/head/delete/(?P<head_id>[0-9]+)/$', RemoveBranchHead.as_view(), name='branch_head_delete'),

    url(r'^dash/employee/creation/$', CreateEmployee.as_view(), name='employee_creation'),
    url(r'^dash/employee/search/$', SearchEmployee.as_view(), name='employee_search'),
    url(r'^dash/employee/edit/(?P<employee_id>[0-9]+)/$', EditEmployee.as_view(), name='employee_edit'),
    url(r'^dash/employee/delete/(?P<employee_id>[0-9]+)/$', RemoveEmployee.as_view(), name='employee_delete'),

    url(r'^dash/customer/creation/$', CreateCustomer.as_view(), name='cusomter_creation'),
    url(r'^dash/customer/search/$', SearchCustomer.as_view(), name='search_customer'),
    url(r'^dash/customer/(?P<customder_id>[0-9]+)/activate/$', ActivateCustomer.as_view(), name='activate_customer'),

    url(r'^dash/account/creation/$', CreateAccount.as_view(), name='account_creation'),
    url(r'^dash/account/ban/search/$', BanSearchAccount.as_view(), name='account_ban_search'),
    url(r'^dash/account/ban/(?P<account_id>[0-9]+)/(?P<ban_unban>[01])/$', BanAccount.as_view(), name='account_ban')
]

Server/funk/forms.py
from dal import autocomplete
from django.contrib.auth.forms import UserCreationForm
from django.forms.widgets import Textarea

from funk.models import Branch, Employee, Customer, Account
from django.forms import ModelForm, ModelChoiceField

class BranchCreationForm(ModelForm):
    class Meta:
        model = Branch
        fields = ['name', 'address', 'total_available_money']
        widgets = {
            'address': Textarea(attrs={'rows':4})
        }
        labels = {
            'name': ('نام شعبه'),
            'address': 'آدرس شعبه (۵۰۰ حرف)',
            'total_available_money': 'موجودی اولیه شعبه'
        }


class BranchEditForm(ModelForm):
    class Meta:
        model = Branch
        fields = ['name', 'address']
        labels = {
            'name': 'نام شعبه',
            'address': 'آدرس شعبه'
        }


class BranchHeadCreationForm(UserCreationForm):
    class Meta:
        model = Employee
        fields = ['national_id', 'name', 'family', 'username', 'password1', 'password2', 'branch']
        labels = {
            'national_id': 'کد ملی',
            'name': 'نام',
            'family': 'نام خانوادگی',
            'branch': 'شعبه'
        }
    branch = ModelChoiceField(queryset=Branch.objects.
                              filter(activation_status=True), label='انتخاب شعبه')


class EmployeeCreationForm(UserCreationForm):
    class Meta:
        model = Employee
        fields = ['national_id', 'name', 'family', 'username', 'role', 'password1', 'password2', 'branch']
        labels = {
            'national_id': 'کد ملی',
            'name': 'نام',
            'family': 'نام خانوادگی',
            'branch': 'شعبه',
            'role': 'نقش'
        }
    branch = ModelChoiceField(queryset=Branch.objects.
                              filter(activation_status=True), label='انتخاب شعبه')


class CustomerCreationForm(UserCreationForm):
    class Meta:
        model = Customer
        fields = ['national_id', 'first_name', 'last_name', 'username', 'password1', 'password2']



class AccountCreationForm(ModelForm):
    class Meta:
        model = Account
        fields = ['customer']
        labels = {
            'customer': 'انتخاب مشتری جهت ایجاد حساب'
        }
        widgets = {
            'customer': autocomplete.ModelSelect2(url='funk:search_user_ajax', attrs={'data-html': 'true'})
        }

    def clean(self):
        cleaned_data = super(AccountCreationForm, self).clean()
        customer = cleaned_data.get('customer')
        if not customer.activation_status:
            self.add_error('customer', 'حساب کاربری مشتری مورد نظر تایید حقوقی نشده است')
        return  cleaned_data


class AccountSearchForm(ModelForm):
    class Meta:
        model = Account
        fields = ['customer',]

        widgets = {
            'customer': autocomplete.ModelSelect2(url='funk:search_user_ajax', attrs={'data-html': 'true'})
        }

Server/funk/views.py
from dal import autocomplete
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db.models.query_utils import Q
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls.base import  reverse_lazy
from django.views.generic.base import View
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from funk.forms import BranchCreationForm, BranchEditForm, BranchHeadCreationForm, EmployeeCreationForm, \
    CustomerCreationForm, AccountCreationForm, AccountSearchForm
from funk.models import Branch, Employee, Customer, Account


class AddUserToContextMixin(object):
    def get_context_data(self, **kwargs):
        c = super(AddUserToContextMixin, self).get_context_data(**kwargs)
        try:
            c['user_info'] = Employee.objects.get(pk=self.request.user.id)
        except:
            c['user_info'] = 'chrt'
        return c


class ShowDash(View):
    def get(self, request):
        print(request.GET.get('message'))
        try:
            user = Employee.objects.get(pk=self.request.user.id)
        except:
            user = 'chrt'
        message = request.GET.get('message', 'خوش آمدید')
        return render(request, 'funk/Dash.html', context={'user_info':user, 'message': message})


class CreateBranch(AddUserToContextMixin, CreateView):
    form_class = BranchCreationForm
    template_name = 'funk/BranchTemplates/BranchCreation.html'
    success_url = '/dash?message='+ 'ثبت شعبه با موفقیت انجام شد'

    def form_valid(self, form):
        m = form.save(commit=False)
        m.activation_status = True
        return super(CreateBranch, self).form_valid(form)



class SearchBranch(AddUserToContextMixin, ListView):
    model = Branch
    context_object_name = 'result'
    template_name = 'funk/BranchTemplates/BranchSearch.html'

    def get_queryset(self):
        branch_name = self.request.GET.get('branch_name', '')
        return Branch.objects.filter(name__icontains=branch_name).filter(activation_status=True)


class RemoveBranch(AddUserToContextMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            user = Employee.objects.get(pk=self.request.user.id)
        except:
            user = 'chrt'
        return render(request, 'funk/BranchTemplates/BranchRemove.html', context={'user_info': user})

    def post(self, request, *args, **kwargs):
        branch = Branch.objects.get(pk=self.kwargs['branch_id'])
        branch.activation_status = False
        branch.save()
        return HttpResponseRedirect('/dash?message='+'حذف شعبه موفقیت آمیز بود')


class EditBranch(AddUserToContextMixin, UpdateView):
    form_class = BranchEditForm
    success_url = '/dash?message='+'به روز رسانی شعبه موفقیت آمیز بود'
    template_name = 'funk/BranchTemplates/BranchEdit.html'

    def get_object(self, queryset=None):
        return Branch.objects.get(pk=self.kwargs['branch_id'])


class CreateBranchHead(AddUserToContextMixin, CreateView):
    form_class = BranchHeadCreationForm
    template_name = 'funk/BranchHeadTemplates/BranchHeadCreation.html'
    success_url = '/dash?message=' + 'ثبت رئیس شعبه با موفقیت انجام شد'

    def form_valid(self, form):
        temp_form = form.save(commit=False)
        temp_form.role = Employee.BRANCH_HEAD_CODE
        return super(CreateBranchHead, self).form_valid(form)


class SearchBranchHead(AddUserToContextMixin, ListView):
    model = Employee
    context_object_name = 'result'
    template_name = 'funk/BranchHeadTemplates/BranchHeadSearch.html'

    def get_queryset(self):
        nid = self.request.GET.get('nid', '')
        name = self.request.GET.get('name', '')
        return Employee.objects.filter(national_id__icontains=nid).filter(name__icontains=name).filter(role=Employee.BRANCH_HEAD_CODE)


class EditBranchHead(AddUserToContextMixin, UpdateView):
    form_class = BranchHeadCreationForm
    template_name = 'funk/BranchHeadTemplates/BranchHeadEdit.html'
    success_url = '/dash?message='+ 'ویرایش رئیس شعبه با موفقیت انجام شد'

    def get_object(self, queryset=None):
        return Employee.objects.get(pk=self.kwargs['head_id'])


class RemoveBranchHead(AddUserToContextMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            user = Employee.objects.get(pk=self.request.user.id)
        except:
            user = 'chrt'
        return render(request, 'funk/BranchHeadTemplates/BranchHeadRemove.html', context={'user_info': user})

    def post(self, request, *args, **kwargs):
        Employee.objects.get(pk=self.kwargs['head_id']).delete()
        return HttpResponseRedirect('/dash?message='+'حذف  رییس شعبه موفقیت آمیز بود')


class CreateEmployee(AddUserToContextMixin, CreateView):
    form_class = EmployeeCreationForm
    template_name = 'funk/BranchManagerTemplates/EmployeeCreationEdit.html'
    success_url = '/dash?message='+ 'کارمند شعبه با موفقیت ثبت شد!'

    def form_valid(self, form):
        temp_form = form.save(commit=False)
        user = Employee.objects.get(pk=self.request.user.id)
        if user.role != Employee.TOTAL_MANAGER_CODE:
            temp_form.branch = user.branch
        return super(CreateEmployee, self).form_valid(form)


class SearchEmployee(AddUserToContextMixin, ListView):
    model = Employee
    context_object_name = 'result'
    template_name = 'funk/BranchManagerTemplates/EmployeeSearch.html'

    def get_queryset(self):
        nid = self.request.GET.get('nid', '')
        name = self.request.GET.get('name', '')
        return Employee.objects.filter(national_id__icontains=nid).filter(name__icontains=name).exclude(role=Employee.BRANCH_HEAD_CODE).exclude(role=Employee.TOTAL_MANAGER_CODE)

class EditEmployee(AddUserToContextMixin, UpdateView):
    form_class = EmployeeCreationForm
    template_name = 'funk/BranchManagerTemplates/EmployeeCreationEdit.html'
    success_url = '/dash?message=' + 'کارمند شعبه با موفقیت ویرایش شد!'

    def form_valid(self, form):
        temp_form = form.save(commit=False)
        user = Employee.objects.get(pk=self.request.user.id)
        if user.role != Employee.TOTAL_MANAGER_CODE:
            temp_form.branch = user.branch
        return super(EditEmployee, self).form_valid(form)

    def get_object(self, queryset=None):
        return Employee.objects.get(pk=self.kwargs['employee_id'])


class RemoveEmployee(AddUserToContextMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            user = Employee.objects.get(pk=self.request.user.id)
        except:
            user = 'chrt'
        return render(request, 'funk/BranchManagerTemplates/EmployeeRemove.html', context={'user_info': user})

    def post(self, request, *args, **kwargs):
        Employee.objects.get(pk=self.kwargs['employee_id']).delete()
        return HttpResponseRedirect('/dash?message='+'حذف  کارمند شعبه موفقیت آمیز بود')


class CreateCustomer(CreateView):
    form_class = CustomerCreationForm
    template_name = 'funk/CustomerTemplates/CustomerCreation.html'
    success_url = '/dash?message='+'ثبت موفق مشتری جدید'


class SearchCustomer(CreateView, ListView):
    model = Customer
    fields = ['first_name', 'last_name', 'activation_status']
    context_object_name = 'result'
    template_name = 'funk/CustomerTemplates/SearchCustomer.html'
    def get_queryset(self):
        form_class = self.get_form_class()
        form = form_class(self.request.GET)
        if not form.is_valid():
            raise ValidationError('yuhahaha')
        first_level_filtered_customers =  Customer.objects.filter(first_name__icontains=form.cleaned_data['first_name']).filter(
            last_name__icontains=form.cleaned_data['last_name']
        )
        if form.cleaned_data['activation_status'] == False:
            first_level_filtered_customers = first_level_filtered_customers.filter(activation_status='False')
        return first_level_filtered_customers
    def post(self, request, *args, **kwargs):
        raise ValidationError('Go fuck yourself')


class ActivateCustomer(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'funk/CustomerTemplates/CustomerActivation.html')

    def post(self, request, *args, **kwargs):
        c = Customer.objects.get(pk=self.kwargs['customder_id'])
        c.activation_status = True
        c.save()
        return HttpResponseRedirect(reverse_lazy('funk:search_customer'))

class CreateAccount(CreateView):
    form_class = AccountCreationForm
    template_name = 'funk/AccountTemplates/AccountCreation.html'

    def get_success_url(self):
        return '/dash?message='+'حساب جدید ثبت شد. شماره حساب ایجاد شده: '+str(self.object.id) + 'برای مشتری: ' + self.object.customer.username


class BanSearchAccount(CreateView, ListView):
    form_class = AccountSearchForm
    context_object_name = 'result'
    template_name = 'funk/AccountTemplates/AccountBanSearch.html'

    def get_queryset(self):
        form_class = self.get_form_class()
        form = form_class(self.request.GET)
        initial_accounts = Account.objects.filter(closed_by_customer=False)
        if form.is_valid() and form.cleaned_data['customer']:
            initial_accounts = initial_accounts.filter(customer=form.cleaned_data['customer'])
        if self.request.GET.get('id',''):
            initial_accounts = initial_accounts.filter(pk=self.request.GET.get('id'))
        if self.request.GET.get('banned',''):
            initial_accounts = initial_accounts.filter(ban_status=True)
        else:
            initial_accounts = initial_accounts.filter(ban_status=False)
        return initial_accounts

    def post(self, request, *args, **kwargs):
        raise ValidationError('Go fuck yourself')

class BanAccount(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'funk/AccountTemplates/AccountBan.html')

    def post(self, request, *args, **kwargs):

Server/funk/templates/funk/Base.html
{% load staticfiles %}
{% load static %}
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <!-- Site Properties -->
    <title>فابانک</title>

    <link rel="stylesheet" href="{% static 'semantic/semantic.min.css' %}">
    <script src="{% static 'semantic/semantic.min.js' %}"></script>
    <script src="{% static 'jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'select2.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'select2.min.css' %}">
    <style type="text/css">
        body {
            background-color: #FFFFFF;
        }

        .ui.menu .item img.logo {
            margin-right: 1.5em;
        }

        .main.container {
            margin-top: 7em;
        }

        .wireframe {
            margin-top: 2em;
        }

        .ui.footer.segment {
            margin: 5em 0em 0em;
            padding: 5em 0em;
        }
    </style>

</head>
<body>

<div class="ui fixed inverted menu" style="flex-direction: row-reverse">
    <div class="ui container">
        <a href="#" class="header item">
            <i class="logo users icon "></i>
            فابانک{{ user_info }}
        </a>
        <a href="/dash" class="item">خانه</a>
        <div class="ui simple dropdown item">
            امور مدیرکلی <i class="dropdown icon"></i>
            <div class="menu">
                <a class="item" href="{% url 'funk:branch_creation' %}">تعریف شعبه</a>
                <a class="item" href="{% url 'funk:branch_search' %}">ویرایش/حذف شعبه</a>
                <div class="divider"></div>
                <a class="item" href="{% url 'funk:branch_head_creation' %}">تعریف رئیس‌شعبه</a>
                <a href="{% url 'funk:branch_head_search' %}" class="item">ویرایش/حذف رئیس شعبه</a>
            </div>
        </div>

        <div class="ui simple dropdown item">
            امور مدیر شعبه <i class="dropdown icon"></i>
            <div class="menu">
                <a class="item" href="{% url 'funk:employee_creation' %}">تعریف کارمند شعبه</a>
                <a class="item" href="{% url 'funk:employee_search' %}">ویرایش/حذف کارمند شعبه</a>
                <div class="divider"></div>

                <a class="item" href="#">Link Item</a>
            </div>
        </div>
        <div class="ui simple dropdown item">
            امور مدیریتی داخل شعبه <i class="dropdown icon"></i>
            <div class="menu">
                <a class="item" href="{% url 'funk:cusomter_creation' %}">تعریف مشتری </a>
                <a class="item" href="{% url 'funk:search_customer' %}">فعال سازی مشتری</a>
                <div class="divider"></div>

                <a class="item" href="{% url 'funk:account_creation' %}">تعریف حساب جدید</a>
                <a class="item" href="{% url 'funk:account_ban_search' %}">مسدود/باز کردن حساب </a>
            </div>
        </div>
        <a href="/logout" class="item">خروج</a>
    </div>
</div>

<div class="ui main text container" style="direction: rtl">
    <h1 class="ui header">
        {% block form_title %}
        Semantic UI Fixed Template
        {% endblock form_title %}
    </h1>
{% block form %}
    <form action="" class="ui large form">

        <input type="text">><input type="text">><input type="text">><input
            type="text">><input type="text">

    </form>
{% endblock form %}

{% block results %}
{% endblock results %}
</div>


{#<div class="ui inverted vertical footer segment">#}
{#    <div class="ui center aligned container">#}
{#        تمام حقوق برای شرکت احسرول محفوظ است#}
{#        <i class="ui icon copyright"></i>#}
{##}
{#        <div class="ui horizontal inverted small divided link list">#}
{#            <a class="item" href="#">راهنما</a>#}
{#            <a class="item" href="#">قوانین</a>#}
{##}
{#        </div>#}
{#    </div>#}
{#</div>#}


</body>
</html>

Server/funk/templates/funk/Dash.html
{% extends 'funk/Base.html' %}
{% block form_title %}
    {{ message }}
{% endblock %}

{% block form %}

{% endblock %}

Server/funk/templates/funk/Welcome.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <script src="{% static 'jquery-3.1.1.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'semantic/semantic.min.css' %}">
    <script src="{% static 'semantic/semantic.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'font/makepersian.css' %}">
    <link rel="stylesheet" type="text/css" href="{%  static 'base.css' %}">
    <title>فابانک</title>
    <script>
        $(document)
            .ready(function() {

                // fix menu when passed
                $('.masthead')
                    .visibility({
                        once: false,
                        onBottomPassed: function() {
                            $('.fixed.menu').transition('fade in');
                        },
                        onBottomPassedReverse: function() {
                            $('.fixed.menu').transition('fade out');
                        }
                    });

                // create sidebar and attach to menu open
                $('.ui.sidebar')
                    .sidebar('attach events', '.toc.item');

            });
    </script>
    <style type="text/css">
        .masthead.segment {
            min-height: 700px;
            padding: 1em 0em;
        }

        .masthead .logo.item img {
            margin-right: 1em;
        }

        .masthead .ui.menu .ui.button {
            margin-left: 0.5em;
        }

        .masthead h1.ui.header {
            margin-top: 3em;
            margin-bottom: 0em;
            font-size: 4em;
            font-weight: normal;
        }

        .masthead h2 {
            font-size: 1.7em;
            font-weight: normal;
        }

        .ui.vertical.stripe {
            padding: 8em 0em;
        }

        .ui.vertical.stripe h3 {
            font-size: 2em;
        }

        .ui.vertical.stripe .button + h3,
        .ui.vertical.stripe p + h3 {
            margin-top: 3em;
        }

        .ui.vertical.stripe .floated.image {
            clear: both;
        }

        .ui.vertical.stripe p {
            font-size: 1.33em;
        }

        .ui.vertical.stripe .horizontal.divider {
            margin: 3em 0em;
        }

        .quote.stripe.segment {
            padding: 0em;
        }

        .quote.stripe.segment .grid .column {
            padding-top: 5em;
            padding-bottom: 5em;
        }

        .footer.segment {
            padding: 5em 0em;
        }

        .secondary.pointing.menu .toc.item {
            display: none;
        }

        @media only screen and (max-width: 700px) {
            .ui.fixed.menu {
                display: none !important;
            }
            .secondary.pointing.menu .item,
            .secondary.pointing.menu .menu {
                display: none;
            }
            .secondary.pointing.menu .toc.item {
                display: block;
            }
            .masthead.segment {
                min-height: 350px;
            }
            .masthead h1.ui.header {
                font-size: 2em;
                margin-top: 1.5em;
            }
            .masthead h2 {
                margin-top: 0.5em;
                font-size: 1.5em;
            }
        }
    </style>
</head>

<body class="pushable">
    <div class="pusher">
        <div class="ui inverted vertical masthead center aligned segment">
            <div class="ui container">
                <div class="ui large secondary inverted pointing menu">
                    <a class="toc item">
                        <i class="sidebar icon"></i>
                    </a>
                    <div class="right item">
                        <a href="login" class="rtl ui inverted button">ورود</a>
                    </div>
                </div>
            </div>
            <div class="ui text container">
                <h1 class="ui inverted  center aligned header"><i class="circular users icon"></i> فا بانک</h1>
                <h2>به سامانه مدیریتی فابانک وارد شوید</h2>
                <a href="login" class="ui huge primary button">ورود به سامانه <i class="right arrow icon"></i></a>
            </div>

        </div>



    </div>

</body>

</html>

Server/funk/templates/funk/login.html
{% load staticfiles %}
<html><head>
  <!-- Standard Meta -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>ورود</title>
    <link rel="stylesheet" href="{% static 'jquery-3.1.1.min.js' %}">
    <link rel="stylesheet" href="{% static 'semantic/semantic.min.css' %}">
    <link rel="stylesheet" href="{% static 'semantic/semantic.min.js    ' %}">

  <style type="text/css">
    body {
      background-color: #DADADA;
    }
    body > .grid {
      height: 100%;
    }
    .image {
      margin-top: -100px;
    }
    .column {
      max-width: 450px;
    }
      input {
          direction: rtl;
      }
  </style>
</head>
<body>

<div class="ui middle aligned center aligned grid">
  <div class="column">
    <h2 class="ui teal image header">
      <i class="circular users icon"></i>
      <div class="content">
            ورود به سامانه فابانک
      </div>
    </h2>
{#    <form class="ui large form">#}
{#      <div class="ui stacked segment">#}
{#        <div class="field">#}
{#          <div class="ui left icon input">#}
{#            <i class="user icon"></i>#}
{#            <input name="email" placeholder="E-mail address" type="text">#}
{#          </div>#}
{#        </div>#}
{#        <div class="field">#}
{#          <div class="ui left icon input">#}
{#            <i class="lock icon"></i>#}
{#            <input name="password" placeholder="Password" type="password">#}
{#          </div>#}
{#        </div>#}
{#        <div class="ui fluid large teal submit button">Login</div>#}
{#      </div>#}
{##}
{#      <div class="ui error message"></div>#}
{##}
{#    </form>#}
      <form action="" method="post" class="ui large form">
            {%  csrf_token %}
          {{ form.as_p }}
          <input type="submit" class="ui fluid large teal submit button" value="ورود">
      </form>
    <div class="ui message">
      اشتباه تایپ نکنید
    </div>
  </div>
</div>




</body></html>